# baseURL: "/data/temp/mycore-hugo/"
baseURL: "/"
canonifyURLs: true
theme: "mycore-bootstrap"

params:
  description: "Some description"
  contentBackgroundColor: "#fff"
  contentTextColor: "#212529"
  contentLinkColor: "#007bff"
  contentLinkHoverColor: "#0056b3"
  navbarBackgroundColor: "#212529"
  navbarLinkColor: "rgba(255, 255, 255, 0.75)"
  navbarLinkHoverColor: "rgba(255, 255, 255, 1)"
  wrapperMaxWidth: "800px"
  customDateFormat: "Jan 2, 2006"
  customCodeStyle: true
  customBlockquoteStyle: true
  showPostSummary: false
  googleAnalytics: "UA-123456789-1"
  cookieConsent: true
  includeBootstrapJs: false
  faviconSafariPinnedTabColor: "#5bbad5"
  faviconMsApplicationTileColor: "#da532c"
  faviconThemeColor: "#ffffff"

pygmentsUseClasses: true

DefaultContentLanguage: de

languages:
    io:
      params:
        flag: "images/flags/iconfinder_Wales_92423.png"
      title: "MyCoRe Webseite"
      description: "Das Framework zur Pr&auml;sentation und Verwaltung digitaler Inhalte."
      languageName: "Beispielseiten"
      weight: 1
      contentDir: content/io
    de:
      params:
        flag: "images/flags/iconfinder_Germany_92095.png"
      title: "MyCoRe Webseite"
      description: "Das Framework zur Pr&auml;sentation und Verwaltung digitaler Inhalte."
      languageName: "Deutsch"
      weight: 2
      contentDir: content/de
    en:
      params:
        flag: "images/flags/iconfinder_United-Kingdom_92403.png"
      title: "MyCoRe Homepage"
      description: "The Framework to present and manage digital contents."
      languageName: "English"
      weight: 3
      contentDir: content/en

summaryLength: 37

permalinks:
  blog: /blog/:year/:month/:slug/
  
#Alternative. Permalinks für Taxonomien, die "/blog/" enthalten
taxonomies:
  period: "blog/periods"
  category: "blog/categories"
  tag: "blog/tags"
  author: "blog/authors"
  